name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU
      run: apt-get install qemu
    - name: Install xbuild
      run: cargo install cargo-xbuild --verbose
    - name: Install rust-src
      run: rustup component add rust-src
    - name: Build
      run: cargo xbuild --verbose
    - name: Run tests
      run: cargo xtest --verbose
