name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install QEMU
      run: sudo apt-get install qemu
    - name: Install bootimage
      run: cargo install bootimage --verbose
    - name: Install rust-src
      run: rustup component add rust-src
    - name: Install llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
